server:
  address: "server:12345"
loop:
  amount: 500
  period: "150ms"
log:
  level: "INFO"
batch:
  maxAmount: 100 # "Maximum" number of bets to send in a batch depending from protocol implementation
